name: Market Update Bot

on:
  workflow_dispatch: # برای اجرای دستی از تب Actions
  schedule:
    - cron: '*/30 * * * *' # هر ۳۰ دقیقه خودکار اجرا شود
  push:
    branches:
      - main # اجرای خودکار به محض هر تغییر در شاخه اصلی

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        run: python bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add market_data.json
          git commit -m "Auto-update market data" || exit 0
          git push
