name: Market Update Bot

on:
  workflow_dispatch: # برای اجرای دستی
  schedule:
    - cron: '*/30 * * * *' # اجرای خودکار هر ۳۰ دقیقه
push:
    branches:
        - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bot
        run: python bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add market_data.json
          git commit -m "Auto-update market data" || exit 0
          git push
